"""Week 4 evaluation: failure labelling + before/after hybrid search comparison.

Usage:
    python scripts/run_week4.py
    python scripts/run_week4.py --no-generation   # skip LLM calls, label from retrieval only

Outputs:
    results/week4_report.md   — the full deliverable report
    results/week4_data.json   — raw data for further analysis
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

from config import RESULTS_DIR, STRATEGIES, TOP_K  # noqa: E402
from eval.questions import QUESTIONS  # noqa: E402
from evaluate import (  # noqa: E402
    evaluate_strategy,
    hit_rate_at,
    hits_at,
    mrr,
)
from failure_labelling import format_label_report, label_all  # noqa: E402
from store import get_collection, query  # noqa: E402


# ---------------------------------------------------------------------------
# Hybrid-aware evaluation: re-run evaluate_strategy using hybrid retrieval
# ---------------------------------------------------------------------------

def evaluate_with_mode(collection, questions, k, mode="semantic"):
    """Run evaluate_strategy but with a specific search mode.

    For 'semantic' this is identical to the existing evaluate_strategy.
    For 'hybrid' or 'bm25', we monkey-patch the query function temporarily.
    """
    if mode == "semantic":
        return evaluate_strategy(collection, questions, k=k)

    # For non-semantic modes, we need to swap the query function used by
    # evaluate_question. Rather than modifying evaluate.py, we build the
    # results manually using the same logic.
    from evaluate import judge
    from retrieve import collection_for

    strategy = None
    for s, coll_name in STRATEGIES.items():
        if coll_name == collection.name:
            strategy = s
            break

    if strategy is None:
        strategy = "structured"

    from retrieve import search as retrieve_search

    per_q = []
    for q in questions:
        hits = retrieve_search(q["question"], strategy=strategy, k=k, mode=mode)
        first_hit = None
        first_answer = None
        rows = []
        for h in hits:
            recipe_ok, section_ok, marker_ok = judge(h, q)
            if recipe_ok and section_ok and first_hit is None:
                first_hit = h["rank"]
            if recipe_ok and marker_ok and first_answer is None:
                first_answer = h["rank"]
            rows.append({
                "rank": h["rank"],
                "chunk_id": h["chunk_id"],
                "recipe_id": (h["metadata"] or {}).get("recipe_id", ""),
                "section": (h["metadata"] or {}).get("section", ""),
                "score": h["score"],
                "distance": h["distance"],
                "correct": bool(recipe_ok and section_ok),
                "has_answer": bool(recipe_ok and marker_ok),
                "snippet": " ".join(h["text"].split())[:150],
            })
        per_q.append({
            "qid": q["qid"],
            "question": q["question"],
            "type": q["type"],
            "gold_recipes": q["gold_recipes"],
            "gold_section": q["gold_section"],
            "expected_answer": q["answer"],
            "first_hit_rank": first_hit,
            "first_answer_rank": first_answer,
            "hit": first_hit is not None,
            "answer_present": first_answer is not None,
            "results": rows,
        })

    return {
        "k": k,
        "hits": sum(1 for r in per_q if r["hit"]),
        "answers": sum(1 for r in per_q if r["answer_present"]),
        "total": len(per_q),
        "per_question": per_q,
    }


# ---------------------------------------------------------------------------
# Report builder
# ---------------------------------------------------------------------------

def build_report(
    strategy,
    baseline_res,
    hybrid_res,
    label_results,
    k,
):
    """Build the Week 4 markdown report."""
    b_pq = baseline_res["per_question"]
    h_pq = hybrid_res["per_question"]
    n = baseline_res["total"]

    L = []
    A = L.append

    A("# Week 4 — Debugging Retrieval: Failure Labelling & Hybrid Search\n")
    A(f"Generated by `scripts/run_week4.py`. Strategy: **{strategy}**, k={k}.\n")

    # ----- Section 1: Failure labelling -----
    A("---\n")
    A("## 1. Failure Classification (Retrieval vs Generation)\n")
    A("Each question is labelled as one of:\n")
    A("- **retrieval_failure** ❌🔍 — the correct document was NOT in top-k. "
      "A smarter model changes nothing; the context was wrong.\n")
    A("- **generation_failure** ❌🤖 — the correct document WAS in top-k, "
      "but the LLM still got the answer wrong.\n")
    A("- **success** ✅ — correct document retrieved, answer is correct.\n")

    A(format_label_report(label_results))

    # ----- Section 2: Before/After -----
    A("\n---\n")
    A("## 2. The One Change: Hybrid Search (BM25 + Semantic + RRF Fusion)\n")
    A("**What changed:** Instead of pure semantic (vector) search, we now combine:\n")
    A("- **Semantic search** — ChromaDB cosine similarity (catches meaning)\n")
    A("- **BM25 keyword search** — exact term matching (catches ingredient names, "
      "codes, exact quantities)\n")
    A("- **Reciprocal Rank Fusion (RRF)** — merges both ranked lists with "
      "`score = Σ 1/(60 + rank)`\n")

    A("\n### Before vs After\n")
    A("| Metric | BEFORE (semantic only) | AFTER (hybrid) | Change |")
    A("| --- | --- | --- | --- |")

    b_hr3 = hit_rate_at(b_pq, 3)
    h_hr3 = hit_rate_at(h_pq, 3)
    b_hr5 = hit_rate_at(b_pq, 5)
    h_hr5 = hit_rate_at(h_pq, 5)
    b_mrr = mrr(b_pq)
    h_mrr = mrr(h_pq)
    b_h3 = hits_at(b_pq, 3)
    h_h3 = hits_at(h_pq, 3)
    b_h5 = hits_at(b_pq, 5)
    h_h5 = hits_at(h_pq, 5)

    def delta(before, after):
        d = after - before
        if d > 0:
            return f"**+{d:.4f}** ⬆️" if isinstance(d, float) else f"**+{d}** ⬆️"
        if d < 0:
            return f"{d:.4f} ⬇️" if isinstance(d, float) else f"{d} ⬇️"
        return "—"

    A(f"| hit-rate@3 | {b_hr3:.4f} ({b_h3}/{n}) | {h_hr3:.4f} ({h_h3}/{n}) | {delta(b_hr3, h_hr3)} |")
    A(f"| hit-rate@5 | {b_hr5:.4f} ({b_h5}/{n}) | {h_hr5:.4f} ({h_h5}/{n}) | {delta(b_hr5, h_hr5)} |")
    A(f"| MRR | {b_mrr:.4f} | {h_mrr:.4f} | {delta(b_mrr, h_mrr)} |")

    # ----- Section 3: Per-question comparison -----
    A("\n### Per-Question Comparison\n")
    A("| Q | Question | BEFORE hit@3 | AFTER hit@3 | BEFORE rank | AFTER rank | Fixed? |")
    A("| --- | --- | --- | --- | --- | --- | --- |")
    for bq, hq in zip(b_pq, h_pq):
        b_rank = bq["first_hit_rank"]
        h_rank = hq["first_hit_rank"]
        b_hit3 = "✅" if (b_rank and b_rank <= 3) else "❌"
        h_hit3 = "✅" if (h_rank and h_rank <= 3) else "❌"
        fixed = ""
        if b_hit3 == "❌" and h_hit3 == "✅":
            fixed = "✅ FIXED"
        elif b_hit3 == "✅" and h_hit3 == "❌":
            fixed = "⚠️ REGRESSED"
        elif b_hit3 == "❌" and h_hit3 == "❌":
            fixed = "— still failing"
        A(f"| {bq['qid']} | {bq['question'][:50]}… | {b_hit3} | {h_hit3} | "
          f"{b_rank or '-'} | {h_rank or '-'} | {fixed} |")

    # ----- Section 4: What was NOT fixed -----
    A("\n### What This Change Did NOT Fix\n")
    still_failing = []
    for bq, hq in zip(b_pq, h_pq):
        h_rank = hq["first_hit_rank"]
        if not (h_rank and h_rank <= 3):
            still_failing.append(hq)

    if still_failing:
        for q in still_failing:
            A(f"- **{q['qid']}**: {q['question']} — "
              f"rank={q['first_hit_rank'] or 'not in top-k'}. "
              f"Gold: {'/'.join(q['gold_recipes'])} / {q['gold_section']}")
        A("\nThese failures need a **different** fix (query rewriting, reranking, "
          "or better chunking) — hybrid search alone cannot resolve them.\n")
    else:
        A("All questions now hit in top-3! 🎉\n")

    # ----- Section 5: Mentor checklist -----
    A("\n---\n")
    A("## 3. Mentor Checklist\n")
    A("| Check | Evidence |")
    A("| --- | --- |")
    A("| Can they show which kind of failure, with evidence? | "
      "Section 1 labels every question with retrieved chunks as proof |")
    A("| Did they make ONE change? | "
      "Yes — hybrid search (BM25 + semantic + RRF). No other changes. |")
    A(f"| Before-and-after number? | "
      f"hit-rate@3: {b_hr3:.4f} → {h_hr3:.4f}, MRR: {b_mrr:.4f} → {h_mrr:.4f} |")
    A("| Did they notice unfixed failures? | "
      f"{'Yes — ' + str(len(still_failing)) + ' questions still fail' if still_failing else 'All fixed'} |")

    return "\n".join(L)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-generation", action="store_true",
                    help="Skip LLM calls, label failures from retrieval only")
    ap.add_argument("--strategy", default="structured", choices=list(STRATEGIES))
    ap.add_argument("--k", type=int, default=TOP_K)
    args = ap.parse_args()

    strategy = args.strategy
    k = args.k
    collection_name = STRATEGIES[strategy]
    coll = get_collection(collection_name)

    print(f"Strategy: {strategy}, k={k}, collection: {collection_name}")

    # ----- Step 1: Baseline (semantic only) -----
    print("\n1. Running BASELINE evaluation (semantic search)...")
    baseline = evaluate_strategy(coll, QUESTIONS, k=k)
    b_pq = baseline["per_question"]
    print(f"   Hit@3: {hits_at(b_pq, 3)}/{baseline['total']}  "
          f"Hit@5: {baseline['hits']}/{baseline['total']}  "
          f"hit-rate@3: {hit_rate_at(b_pq, 3):.4f}  "
          f"MRR: {mrr(b_pq):.4f}")

    # ----- Step 2: Label failures -----
    print("\n2. Labelling failures (retrieval vs generation)...")
    run_gen = not args.no_generation
    labels = label_all(coll, QUESTIONS, k=k, run_generation=run_gen)
    c = labels["counts"]
    print(f"   Success: {c['success']}, Retrieval failures: {c['retrieval_failure']}, "
          f"Generation failures: {c['generation_failure']}")
    for r in labels["per_question"]:
        emoji = {"success": "✅", "retrieval_failure": "❌🔍", "generation_failure": "❌🤖"}
        print(f"   {r['qid']}: {emoji.get(r['label'], '')} {r['label']}")

    # ----- Step 3: Hybrid search (the ONE change) -----
    print("\n3. Running HYBRID evaluation (BM25 + semantic + RRF)...")
    hybrid = evaluate_with_mode(coll, QUESTIONS, k=k, mode="hybrid")
    h_pq = hybrid["per_question"]
    print(f"   Hit@3: {hits_at(h_pq, 3)}/{hybrid['total']}  "
          f"Hit@5: {hybrid['hits']}/{hybrid['total']}  "
          f"hit-rate@3: {hit_rate_at(h_pq, 3):.4f}  "
          f"MRR: {mrr(h_pq):.4f}")

    # ----- Step 4: Build report -----
    print("\n4. Building report...")
    report = build_report(strategy, baseline, hybrid, labels, k)

    RESULTS_DIR.mkdir(exist_ok=True)
    report_path = RESULTS_DIR / "week4_report.md"
    report_path.write_text(report, encoding="utf-8")

    # Save raw data
    data = {
        "strategy": strategy,
        "k": k,
        "baseline": {
            "hits": baseline["hits"],
            "total": baseline["total"],
            "hit_rate_3": hit_rate_at(b_pq, 3),
            "hit_rate_5": hit_rate_at(b_pq, 5),
            "mrr": mrr(b_pq),
        },
        "hybrid": {
            "hits": hybrid["hits"],
            "total": hybrid["total"],
            "hit_rate_3": hit_rate_at(h_pq, 3),
            "hit_rate_5": hit_rate_at(h_pq, 5),
            "mrr": mrr(h_pq),
        },
        "labels": labels,
    }
    data_path = RESULTS_DIR / "week4_data.json"
    data_path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")

    print(f"\n✅ Done!")
    print(f"   Report: {report_path}")
    print(f"   Data:   {data_path}")

    # Print the headline comparison
    print(f"\n{'='*60}")
    print(f"  BEFORE (semantic): hit-rate@3 = {hit_rate_at(b_pq, 3):.4f}, MRR = {mrr(b_pq):.4f}")
    print(f"  AFTER  (hybrid):   hit-rate@3 = {hit_rate_at(h_pq, 3):.4f}, MRR = {mrr(h_pq):.4f}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
